apiVersion: v1
kind: Secret
metadata:
  name: harborsecret120
  namespace: bj-k8snfs
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxNzIuMjkuMTQxLjEyMCI6IHsKCQkJImF1dGgiOiAiYkdsMWREQXdNanBRY21sdVkyVXhNREF6IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: bj-k8snfs
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      imagePullSecrets:
      - name: harborsecret120
      serviceAccountName: nfs-client-provisioner
      containers:
      - name: nfs-client-provisioner
        image: 172.29.141.120/lt/nfs-subdir-external-provisioner:v4.0.2
        volumeMounts:
        - name: nfs-client-root
          mountPath: /persistentvolumes
        env:
        - name: PROVISIONER_NAME
          value: k8s-sigs.io/nfs-subdir-external-provisioner
        - name: NFS_SERVER
          value: 172.29.141.25
        - name: NFS_PATH
          value: /data/nfs_data01
      volumes:
      - name: nfs-client-root
        nfs:
          server: 172.29.141.25
          path: /data/nfs_data01
