apiVersion: v1
kind: Service
metadata:
  labels:
    app: bj-alertmanager01
  name: bj-alertmanager01-service
  namespace: bj-promtheus
spec:
  type: LoadBalancer
  loadBalancerIP: 172.29.141.117
  ports:
  - name: tcp9093
    protocol: TCP
    port: 9093
    targetPort: 9093
  selector:
    app: bj-alertmanager01
