apiVersion: apps/v1
kind: Deployment
metadata:
  name: bj-alertmanager01-deployment
  namespace: bj-promtheus
  labels:
    app: bj-alertmanager01
    version: alertmanager-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bj-alertmanager01
  template:
    metadata:
      labels:
        app: bj-alertmanager01
    spec:
      imagePullSecrets:
      - name: harborsecret120
      containers:
      - name: bj-alertmanager01
        image: 172.29.141.120/lt/prom/alertmanager:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9093
          protocol: TCP
          name: tcp9093
        volumeMounts:
        - name: alertmanager01
          mountPath: /etc/alertmanager
        - name: localtime
          mountPath: /etc/localtime
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
          requests:
            cpu: "500m"
            memory: "123Mi"
      volumes:
      - name: alertmanager01
        persistentVolumeClaim:
          claimName: alertmanager01-claim
      - name: localtime
        hostPath:
          path: "/etc/localtime"

