version: '2.3'
services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: prometheus
    volumes:
    - /data/alertmanager:/etc/alertmanager
    - /etc/localtime:/etc/localtime:ro
    command:
    - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
    - 9093:9093
    restart: always
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
    - '--path.rootfs=/host'
    - '--no-collector.nvme'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
    - '/:/host:ro,rslave'
