version: "2.3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
    - /data/prometheus/config:/etc/prometheus
    - /data/prometheus/data:/prometheus
    - /etc/localtime:/etc/localtime:ro
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    ports:
    - "9090:9090"
    depends_on:
    - influxdb
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    hostname: influxdb
    restart: always
    volumes:
    - /data/influxdb/config:/etc/influxdb
    - /data/influxdb/data:/var/lib/influxdb/data
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "8086:8086"
    - "8083:8083"
    environment:
    - INFLUXDB_DB=prometheus
    - INFLUXDB_ADMIN_ENABLED=true
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=adminpwd
    - INFLUXDB_USER=prometheus
    - INFLUXDB_USER_PASSWORD=prometheuspwd
    - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - "8080:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
    - '--path.rootfs=/host'
    - '--no-collector.nvme'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
    - '/:/host:ro,rslave'
