apiVersion: v1
kind: Service
metadata:
  labels:
    app: bj-promtheus01
  name: bj-promtheus01-service
  namespace: bj-promtheus
spec:
  type: LoadBalancer
  loadBalancerIP: 172.29.141.112
  ports:
  - name: tcp9090
    protocol: TCP
    port: 9090
    targetPort: 9090
  - name: tcp8086
    protocol: TCP
    port: 8086
    targetPort: 8086
  - name: tcp8083
    protocol: TCP
    port: 8083
    targetPort: 8083
  selector:
    app: bj-promtheus01
