apiVersion: apps/v1
kind: Deployment
metadata:
  name: bj-promtheus01-deployment
  namespace: bj-promtheus
  labels:
    app: bj-promtheus01
    version: bj-promtheus-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bj-promtheus01
  template:
    metadata:
      labels:
        app: bj-promtheus01
    spec:
      imagePullSecrets:
      - name: harborsecret120
      containers:
      - name: bj-promtheus01
        image: 172.29.141.120/lt/prom/prometheus:v1
        imagePullPolicy: IfNotPresent
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        ports:
        - containerPort: 9090
          protocol: TCP
          name: tcp9090
        volumeMounts:
        - name: bj-promtheus01-data
          mountPath: /etc/prometheus
          subPath: data/prometheus/config
          readOnly: false
        - name: bj-promtheus01-data
          mountPath: /prometheus
          subPath: data/prometheus/data
          readOnly: false
        - name: bj-promtheus01-localtime
          mountPath: /etc/localtime
          readOnly: true
        resources:
          limits:
            cpu: 2000m
            memory: 4096Mi
          requests:
            cpu: 100m
            memory: 50Mi
      - name: bj-influxdb01
        image: 172.29.141.120/lt/influxdb:1.8
        imagePullPolicy: IfNotPresent
        env:
        - name: "INFLUXDB_DB"
          value: "prometheus"
        - name: "INFLUXDB_ADMIN_ENABLED"
          value: "true"
        - name: "INFLUXDB_ADMIN_USER"
          value: "admin"
        - name: "INFLUXDB_ADMIN_PASSWORD"
          value: "adminpwd"
        - name: "INFLUXDB_USER"
          value: "prometheus"
        - name: "INFLUXDB_USER_PASSWORD"
          value: "prometheuspwd"
        - name: "INFLUXDB_CONFIG_PATH"
          value: "/etc/influxdb/influxdb.conf"
        ports:
        - containerPort: 8086
          protocol: TCP
          name: tcp8086
        - containerPort: 8083
          protocol: TCP
          name: tcp8083
        volumeMounts:
        - name: bj-promtheus01-data
          mountPath: /etc/influxdb
          subPath: data/influxdb/config
          readOnly: false
        - name: bj-promtheus01-data
          mountPath: /var/lib/influxdb/data
          subPath: data/influxdb/data
          readOnly: false
        - name: bj-promtheus01-localtime
          mountPath: /etc/localtime
          readOnly: true
        resources:
          limits:
            cpu: 2000m
            memory: 4096Mi
          requests:
            cpu: 100m
            memory: 50Mi
      volumes:
      - name: bj-promtheus01-data
        persistentVolumeClaim:
          claimName: bj-promtheus01-claim
      - name: bj-promtheus01-localtime
        hostPath:
          path: "/etc/localtime"
