apiVersion: apps/v1
kind: Deployment
metadata:
  name: bj-squid01-deployment
  namespace: bj-squid
  labels:
    app: bj-squid01
    version: bj-squid-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bj-squid01
  template:
    metadata:
      labels:
        app: bj-squid01
    spec:
      imagePullSecrets:
      - name: harborsecret120
      containers:
      - name: bj-squid01
        image: 172.29.141.120/lt/ubuntu/squid:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3128
          protocol: TCP
          name: tcp3128
        resources:
          limits:
            cpu: 2000m
            memory: 4096Mi
          requests:
            cpu: 100m
            memory: 50Mi


