apiVersion: v1
kind: Service
metadata:
  labels:
    app: bj-squid01
  name: bj-squid01-service
  namespace: bj-squid
spec:
  type: LoadBalancer
  loadBalancerIP: 172.29.141.130
  ports:
  - name: tcp3128
    protocol: TCP
    port: 3128
    targetPort: 3128
  selector:
    app: bj-squid01
