- name: Disable any MD5 or 96-bit HMAC algorithms within the SSH configuration
  hosts: all
  gather_facts: no

  tasks:
  - name: View sshd_config.
    shell: cat /etc/ssh/sshd_config |grep "MACs umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512" |wc -l
    register: result
  - name: Determine if disable MD5 or 96-bit HMAC algorithm
    debug:
      msg: The MD5 or 96-bit HMAC algorithm has been disabled.
    when: result.stdout == "1"
  - name: If not disabled, disables MD5 or 96-bit HMAC
    shell:
      cmd: 'echo "MACs umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512" >> /etc/ssh/sshd_config'
    when: result.stdout == "0"
    notify: restart sshd
  - name: Recheck if disable MD5 or 96-bit HMAC algorithm
    shell: cat /etc/ssh/sshd_config |grep "MACs umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512" |wc -l
    register: result_1
  - name: Executed successfully
    debug:
      msg: Executed successfully.
    when: result_1.stdout == "1"
  - name: Execution failure
    debug:
      msg: Execution failure.
    when: result_1.stdout == "0"

  handlers:
  - name: restart sshd
    service: name=sshd state=restarted
