- name: Disable SSH support for CBC cipher suite
  hosts: all
  gather_facts: no

  tasks:
  - name: View sshd_config
    shell: cat /etc/ssh/sshd_config |grep "Ciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com" |wc -l
    register: result
  - name: Determine if the specified encryption algorithm is CRT
    debug:
      msg: SSH has been set to the CTR mode.
    when: result.stdout == "1"
  - name: If not specified, specify the encryption algorithm as CRT
    shell:
      cmd: 'echo "Ciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com" >> /etc/ssh/sshd_config'
    when: result.stdout == "0"
    notify: restart sshd
  - name: Recheck if the specified encryption algorithm is CRT
    shell: cat /etc/ssh/sshd_config |grep "Ciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com" |wc -l
    register: result_1
  - name: Encryption algorithm is CRT
    debug:
      msg: SSH has been set to the CTR mode.
    when: result_1.stdout == "1"
  - name: Encryption algorithm is not CRT
    debug:
      msg: SSH is not set to the CTR mode.
    when: result_1.stdout == "0"

  handlers:
  - name: restart sshd
    service: name=sshd state=restarted

