apiVersion: v1
kind: Secret
metadata:
  name: harborsecret120
  namespace: bj-chrony
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxNzIuMjkuMTQxLjEyMCI6IHsKCQkJImF1dGgiOiAiYkdsMWREQXdNanBRY21sdVkyVXhNREF6IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
