apiVersion: v1
kind: Service
metadata:
  labels:
    app: bj-chrony01
  name: bj-chrony01-service
  namespace: bj-chrony
spec:
  type: LoadBalancer
  loadBalancerIP: 172.29.141.113
  ports:
  - name: udp123
    protocol: UDP
    port: 123
    targetPort: 123
  selector:
    app: bj-chrony01
