apiVersion: v1
kind: Namespace
metadata:
  name: bj-chrony
  labels:
    name: bj-chrony

---
apiVersion: v1
kind: Secret
metadata:
  name: harborsecret120
  namespace: bj-chrony
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxNzIuMjkuMTQxLjEyMCI6IHsKCQkJImF1dGgiOiAiYkdsMWREQXdNanBRY21sdVkyVXhNREF6IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bj-chrony01-deployment
  namespace: bj-chrony
  labels:
    app: bj-chrony01
    version: bj-chrony-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bj-chrony01
  template:
    metadata:
      labels:
        app: bj-chrony01
    spec:
      imagePullSecrets:
      - name: harborsecret120
      containers:
      - name: bj-chrony01
        image: 172.29.141.120/lt/chrony:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 123
          protocol: UDP
          name: udp123
        env:
        - name: "NTP_SERVERS"
          value: "ntp1.aliyun.com,ntp2.aliyun.com,ntp3.aliyun.com,ntp4.aliyun.com"
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 100m
            memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bj-chrony01
  name: bj-chrony01-service
  namespace: bj-chrony
spec:
  type: LoadBalancer
  loadBalancerIP: 172.29.141.53
  ports:
  - name: udp123
    protocol: UDP
    port: 123
    targetPort: 123
  selector:
    app: bj-chrony01
