apiVersion: v1
kind: Namespace
metadata:
  name: bj-nginx
  labels:
    name: bj-nginx

---
apiVersion: v1
kind: Secret
metadata:
  name: harborsecret120
  namespace: bj-nginx
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxNzIuMjkuMTQxLjEyMCI6IHsKCQkJImF1dGgiOiAiYkdsMWREQXdNanBRY21sdVkyVXhNREF6IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bj-nginx01-deployment
  namespace: bj-nginx
  labels:
    app: bj-nginx01
    version: bj-nginx01-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bj-nginx01
  template:
    metadata:
      labels:
        app: bj-nginx01
    spec:
      imagePullSecrets:
      - name: harborsecret120
      containers:
      - name: bj-nginx01
        image: 172.29.141.120/lt/nagix:1.21.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
          name: tcp80
        volumeMounts:
        - name: nginxvolume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginxvolume
        nfs:
          server: 172.29.141.23
          path: /data/nfs_data01

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bj-nginx01
  name: bj-nginx01-service
  namespace: bj-nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 172.29.141.54
  ports:
  - name: tcp80
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: bj-nginx01
